question_2/config/routes.rb
Question2::Application.routes.draw do
  post '/login' => 'sessions#login', as: 'login'
  delete '/logout' => 'sessions#logout', as: 'logout'

  root to: 'top#index'

  resources :publications, except: [:edit, :udpate, :destroy] do
    member do
      put :add_author
      put :add_skilltag
    end
  end

  resources :users, only: :show do
    resources :skilltags, only: :create
  end

  get '/skilltags/:name' => 'skilltags#show', as: 'skilltag'
  get '/users/tagged/:name' => 'skilltags/users#index', as: 'tagged_users'

end

question_2/app/models/publication.rb
class Publication < ActiveRecord::Base
  attr_accessible :category, :title, :url

  has_many :user_publications
  has_many :users, through: :user_publications

  has_many :publication_skilltags
  has_many :skilltags, through: :publication_skilltags
end

question_2/app/models/publication_skilltag.rb
class PublicationSkilltag < ActiveRecord::Base
  attr_accessible :publication_id, :skilltag_id

  belongs_to :publication
  belongs_to :skilltag
end

question_2/app/models/skilltag.rb
class Skilltag < ActiveRecord::Base
  attr_accessible :name

  has_many :publication_skilltags
  has_many :publications, through: :publication_skilltags

  has_many :user_skilltags
  has_many :users, through: :user_skilltags
end

question_2/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :username

  has_many :user_publications
  has_many :publications, through: :user_publications

  has_many :user_skilltags
  has_many :skilltags, through: :user_skilltags
end

question_2/app/models/user_publication.rb
class UserPublication < ActiveRecord::Base
  attr_accessible :publication_id, :user_id

  belongs_to :user
  belongs_to :publication
end

question_2/app/models/user_skilltag.rb
class UserSkilltag < ActiveRecord::Base
  attr_accessible :skilltag_id, :user_id

  belongs_to :user
  belongs_to :skilltag
end

question_2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user, :user_signed_in?

  def current_user
    @current_user ||= User.find(session[:current_user])
  rescue ActiveRecord::RecordNotFound
    nil
  end

  def user_signed_in?
    !!current_user
  end
end

question_2/app/controllers/publications_controller.rb
# coding: utf-8
class PublicationsController < ApplicationController
  def index
    @publications = Publication.order('created_at desc').page(params[:page]).per(10)
  end

  def show
    @publication = Publication.find params[:id]
  end

  def new
    @publication = Publication.new
  end

  def create
    @publication = Publication.new params[:publication]
    @publication.users << current_user

    if @publication.save
      redirect_to @publication, notice: "#{@publication.title}を登録しました"
    else
      render 'new'
    end
  end

  def add_author
    @publication = Publication.find params[:id]

    if @publication.users << current_user
      redirect_to @publication, notice: "#{@publication.title}の著者にあなたを追加しました"
    else
      redirect_to @publication, notice: "#{@publication.title}の著者にあなたを追加できませんでした。"
    end
  end

  def add_skilltag
    @publication = Publication.find params[:id]
    @skilltag = Skilltag.where(name: params[:skilltag]).first_or_create!

    if @publication.skilltags << @skilltag
      redirect_to @publication, notice: "#{@publication.title}のスキルに#{@skilltag.name}を追加しました"
    else
      redirect_to @publication, notice: "#{@publication.title}のスキルに#{@skilltag.name}を追加できませんでした"
    end
  end
end

question_2/app/controllers/sessions_controller.rb
# coding: utf-8
class SessionsController < ApplicationController
  def login
    session[:current_user] = 1
    redirect_to root_path
  end

  def logout
    session[:current_user] = nil
    current_user = nil

    redirect_to root_path
  end
end

question_2/app/controllers/skilltags/users_controller.rb
# coding: utf-8
class Skilltags::UsersController < ApplicationController
  def index
    @skilltag = Skilltag.find_by_name params[:name]
    raise ActiveRecord::RecordNotFound if @skilltag.nil?

    @users = @skilltag.users.all
  end
end

question_2/app/controllers/skilltags_controller.rb
# coding: utf-8
class SkilltagsController < ApplicationController
  def show
    @skilltag = Skilltag.find_by_name params[:name]
    raise ActiveRecord::RecordNotFound if @skilltag.nil?
  end

  # POST /users/:user_id/skilltags
  def create
    @user = User.find params[:user_id]
    @skilltag = Skilltag.where(name: params[:skilltag][:name]).first_or_initialize

    return redirect_to @user, notice: "すでに登録済みです" if @user.skilltags.include? @skilltag

    if @user.skilltags << @skilltag
      redirect_to @user, notice: "#{@skilltag.name}を登録しました"
    else
      redirect_to @user, notice: "#{@skilltag.name}を登録できませんでした"
    end
  end
end

question_2/app/controllers/top_controller.rb
# coding: utf-8
class TopController < ApplicationController
  def index
  end
end

question_2/app/controllers/users_controller.rb
# coding: utf-8
class UsersController < ApplicationController
  def show
    @user = User.find params[:id]
  end
end

question_2/app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Question2
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    - if notice
      %p.notice= notice

    = yield

question_2/app/views/publications/index.html.haml
- @publications.each do |publication|
  .publication
    %h2= link_to publication.title, publication
    %p= link_to publication.url.gsub(/https?:\/\//, ''), publication.url
= paginate @publications

question_2/app/views/publications/new.html.haml
= form_for @publication do |f|
  - if @publication.errors.any?
    #error_explanation
      %h2= "#{pluralize(@publication.errors.count, "error")} prohibited this skilltag from being saved:"
      %ul
        - @publication.errors.full_messages.each do |msg|
          %li= msg
  %dl
    %dt= f.label :title
    %dd= f.text_field :title

  %dl
    %dt= f.label :url
    %dd= f.text_field :url

  = f.submit 'Save'

question_2/app/views/publications/show.html.haml
.publication
  %header
    %h1= @publication.title

  %p= link_to @publication.url.gsub(/https?:\/\//, ''), @publication.url

  %ul
    - @publication.skilltags.each do |skilltag|
      %li= skilltag.name
    - if user_signed_in?
      %li
        = form_tag add_skilltag_publication_path(@publication), method: :put do
          = text_field_tag :skilltag
          = submit_tag 'スキルタグ登録する'

  %ul
    - @publication.users.each do |user|
      %li= user.username
    - if user_signed_in? && !@publication.users.include?(current_user)
      %li= link_to '自分を著者に登録', add_author_publication_path(@publication), method: :put

%nav
  = link_to 'Back', publications_path

question_2/app/views/skilltags/show.html.haml
%header
  %h1= @skilltag.name

  %p
    %span
      ユーザー数:
      = @skilltag.users.count
    %span
      書いたもの数:
      = @skilltag.publications.count

.skilltag-nav
  %nav
    %ul
      %li= link_to '書いたもの', skilltag_path(name: @skilltag.name)

.body
  - @skilltag.publications.each do |pub|
    .publication
      %article
        %header
          %h2= link_to pub.title, pub
        %ul
          - pub.skilltags.each do |skilltag|
            %li= link_to skilltag.name, skilltag_path(name: skilltag.name)

question_2/app/views/skilltags/users/index.html.haml
%header
  %h1= @skilltag.name

  %p
    %span
      ユーザー数:
      = @skilltag.users.count
    %span
      書いたもの数:
      = @skilltag.publications.count

.skilltag-nav
  %nav
    %ul
      %li= link_to '書いたもの', skilltag_path(name: @skilltag.name)
      %li= 'ユーザー'

.body
  - @skilltag.users.each do |user|
    .user
      %article
        %header
          %h2= link_to "#{user.last_name} #{user.first_name}", user
        %ul
          - user.skilltags.each do |skilltag|
            %li= link_to skilltag.name, skilltag_path(name: skilltag.name)

question_2/app/views/top/index.html.haml
%h1 Top

= link_to '一覧へ', publications_path

- if user_signed_in?
  %h2= "Hello, #{current_user.username}!!"
  %p= link_to 'logout', logout_path, method: :delete
- else
  %p= link_to 'login', login_path, method: :post

question_2/app/views/users/show.html.haml
.header
  %header
    %h1= "#{@user.first_name} #{@user.last_name}"

  %ul
    - @user.skilltags.each do |skilltag|
      %li= skilltag.name
    - if user_signed_in? && @user == current_user
      %li
        = form_for [@user, Skilltag.new] do |f|
          = f.text_field :name
          = f.submit '登録する'